# Generated by Django 5.2.7 on 2025-10-15 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64, unique=True)),
                ('size', models.CharField(blank=True, max_length=32)),
                ('image_url', models.URLField(blank=True)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty', models.IntegerField(default=0)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_item', models.ForeignKey(db_column='task_item_code', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='taskmaster.taskitem', to_field='item_code')),
            ],
            options={
                'ordering': ['barcode'],
            },
        ),
    ]
