# Generated by Django 5.2.7 on 2025-10-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('taskmaster', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stf_out', to='taskmaster.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stf_in', to='taskmaster.location')),
            ],
            options={
                'ordering': ['-created_at', 'number'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='products.stocktransfer')),
            ],
            options={
                'ordering': ['barcode'],
                'indexes': [models.Index(fields=['barcode'], name='products_st_barcode_2f7cea_idx')],
            },
        ),
    ]
