# Generated by Django 5.2.7 on 2025-10-25 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_invoicesequence_customer_sale_saleline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='CN', max_length=16, unique=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('pad_width', models.PositiveSmallIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='products.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='products.sale')),
            ],
            options={
                'ordering': ['-note_date', '-id'],
                'indexes': [models.Index(fields=['barcode'], name='products_cr_barcode_311c0d_idx')],
            },
        ),
    ]
