# Generated by Django 5.2.7 on 2025-10-25 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_creditnotesequence_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
