# Generated by Django 5.2.7 on 2025-10-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_creditnote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotesequence',
            name='pad_width',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='creditnotesequence',
            name='prefix',
            field=models.CharField(default='CRN', max_length=16, unique=True),
        ),
    ]
