# Generated by Django 5.2.7 on 2025-10-27 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_creditnotesequence_pad_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='amount_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='last_redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='last_redeemed_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_credit_notes', to='products.sale'),
        ),
        migrations.AlterField(
            model_name='creditnotesequence',
            name='pad_width',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='creditnotesequence',
            name='prefix',
            field=models.CharField(default='CN', max_length=16, unique=True),
        ),
    ]
