# Generated by Django 5.2.7 on 2025-10-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_creditnote_amount_used_creditnote_last_redeemed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='amount_used',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='last_redeemed_at',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='last_redeemed_sale',
        ),
        migrations.AlterField(
            model_name='creditnotesequence',
            name='pad_width',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='creditnotesequence',
            name='prefix',
            field=models.CharField(default='CRN', max_length=16, unique=True),
        ),
    ]
