# Generated by Django 5.2.7 on 2025-10-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_creditnote_amount_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='redeemed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='redeemed_invoice',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
