# Generated by Django 5.2.7 on 2025-10-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_creditnote_is_redeemed_creditnote_redeemed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('CASH', 'Cash'), ('MULTIPAY', 'Multipay'), ('CREDIT', 'Credit Note')], max_length=16),
        ),
    ]
