# Generated by Django 5.2.7 on 2025-10-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesequence',
            name='prefix',
            field=models.CharField(default='INV', max_length=16, unique=True),
        ),
    ]
