# Generated by Django 5.2.7 on 2025-10-31 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_invoicesequence_prefix'),
        ('taskmaster', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('items_total', models.PositiveIntegerField(default=0)),
                ('qty_total', models.PositiveIntegerField(default=0)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MasterPackLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('brand', models.CharField(blank=True, default='B4L', max_length=64)),
                ('color', models.CharField(blank=True, default='', max_length=64)),
                ('size', models.CharField(blank=True, default='', max_length=32)),
                ('sp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_pack_lines', to='taskmaster.location')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='products.masterpack')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['barcode'],
                'indexes': [models.Index(fields=['barcode'], name='products_ma_barcode_49f7a0_idx')],
            },
        ),
    ]
