# Generated by Django 5.2.7 on 2025-11-01 10:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_masterpack_masterpackline'),
        ('taskmaster', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConsumptionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='CONWS', max_length=16, unique=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('pad_width', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('consumption_type', models.CharField(default='Production', max_length=32)),
                ('remark', models.TextField(blank=True, default='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='taskmaster.location')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='products.materialconsumption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'ordering': ['barcode'],
                'indexes': [models.Index(fields=['barcode'], name='products_ma_barcode_c2170c_idx')],
            },
        ),
    ]
