# Generated by Django 5.2.7 on 2025-11-03 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_materialconsumptionsequence_materialconsumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('recommended', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='products.customer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='products.sale')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
