# Generated by Django 5.2.7 on 2025-11-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_salefeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleFeedback',
        ),
    ]
