# Generated by Django 5.2.7 on 2025-11-04 05:32

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_delete_salefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Coupon name must be alphanumeric (A–Z, a–z, 0–9) without spaces.', regex='^[A-Za-z0-9]+$')])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='coupon_name_unique_ci')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField()),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issued_by', models.CharField(default='Vishnu', max_length=64)),
                ('customer_no', models.CharField(blank=True, default='', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('redemption_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REDEEMED', 'Redeemed')], default='AVAILABLE', max_length=16)),
                ('redeemed_invoice_no', models.CharField(blank=True, default='', max_length=32)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='products.coupon')),
            ],
            options={
                'ordering': ['-created_date', '-id'],
                'indexes': [models.Index(fields=['code'], name='products_ge_code_073096_idx'), models.Index(fields=['coupon', 'serial_no'], name='products_ge_coupon__a0cc06_idx')],
            },
        ),
    ]
