# Generated by Django 5.2.7 on 2025-11-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_coupon_generatedcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('CASH', 'Cash'), ('MULTIPAY', 'Multipay'), ('CREDIT', 'Credit Note'), ('COUPON', 'Coupon')], max_length=16),
        ),
    ]
