# Generated by Django 5.2.7 on 2025-11-12 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_sale_payment_method'),
        ('taskmaster', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('code', models.CharField(db_index=True, max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Discount Code must be 6 characters, capital letters & digits (e.g. RDF214).', regex='^[A-Z0-9]{6}$')])),
                ('applicable', models.CharField(choices=[('PRODUCT', 'Product wise'), ('BILL', 'Entire bill')], default='PRODUCT', max_length=16)),
                ('mode', models.CharField(choices=[('NORMAL', 'Normal'), ('RANGE', 'Range wise'), ('BUYXGETY', 'Buy X Get Y'), ('FIXPRICE', 'Product at Fix Amount')], default='NORMAL', max_length=16)),
                ('value_type', models.CharField(choices=[('PERCENT', '%'), ('AMOUNT', '₹')], default='PERCENT', max_length=8)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('range_min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('range_max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('x_qty', models.PositiveIntegerField(default=0)),
                ('y_qty', models.PositiveIntegerField(default=0)),
                ('min_amount_for_fix', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applies_category', models.CharField(blank=True, default='', max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branches', models.ManyToManyField(related_name='discounts', to='taskmaster.location')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
