# Generated by Django 5.2.7 on 2025-12-01 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_holdbillsequence_holdbill_holdbillline'),
        ('taskmaster', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='taskmaster.location'),
        ),
    ]
