# Generated by Django 5.2.7 on 2025-12-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=120)),
                ('group_nature', models.CharField(choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Expenses', 'Expenses'), ('Income', 'Income')], default='Assets', max_length=32)),
                ('account_type', models.CharField(default='customers', max_length=32)),
                ('opening_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location_name', models.CharField(default='Brands 4 less - IFFCO Chowk', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
