# Generated by Django 5.2.7 on 2025-12-03 08:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0007_alter_employee_aadhaar_alter_employee_pan'),
        ('products', '0022_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('non_gst', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='products.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='outlets.employee')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='products.supplier')),
            ],
            options={
                'ordering': ['-date_time', '-id'],
            },
        ),
    ]
