# Generated by Django 5.2.7 on 2025-12-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0008_wowbillentry_bill_date_wowbillentry_customer_and_more'),
        ('products', '0023_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='outlets.employee'),
        ),
    ]
