# Generated by Django 5.2.7 on 2025-12-06 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0009_wowbillslab'),
        ('products', '0024_sale_salesman'),
        ('taskmaster', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cheque_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_transfer_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upi_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wallet_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_return', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_refund', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_refund', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pay_later', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_account', models.CharField(blank=True, default='', max_length=120)),
                ('bank_transfer_register', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_left', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('physical_drawer', models.CharField(choices=[('TOTAL_CASH', 'Total Cash'), ('SHORT', 'Short'), ('EXCESS', 'Excess')], default='TOTAL_CASH', max_length=16)),
                ('closing_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_closings', to='outlets.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register_closings', to='taskmaster.location')),
            ],
            options={
                'ordering': ['-closed_at', '-id'],
            },
        ),
    ]
