# Generated by Django 5.2.7 on 2026-01-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('CASH', 'Cash'), ('MULTIPAY', 'Multipay'), ('CREDIT', 'Credit Note'), ('COUPON', 'Coupon')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('card_holder', models.CharField(blank=True, default='', max_length=120)),
                ('card_holder_phone', models.CharField(blank=True, default='', max_length=20)),
                ('customer_bank', models.CharField(blank=True, default='', max_length=120)),
                ('account', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='products.sale')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['method'], name='products_sa_method_1bbc70_idx')],
            },
        ),
    ]
