# Generated by Django 5.2.7 on 2026-01-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_creditnote_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
