# Generated by Django 5.2.7 on 2026-02-02 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0009_wowbillslab'),
        ('products', '0032_customer_created_by_customer_location'),
        ('taskmaster', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_sessions', to='outlets.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register_sessions', to='taskmaster.location')),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('location', 'business_date'), name='uniq_register_session_location_day')],
            },
        ),
    ]
