# Generated by Django 5.2.7 on 2026-02-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_registersession'),
        ('taskmaster', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpack',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_packs_from', to='taskmaster.location'),
        ),
        migrations.AddField(
            model_name='masterpack',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_packs_to', to='taskmaster.location'),
        ),
    ]
