# Generated by Django 5.2.7 on 2026-02-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_masterpack_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPackSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(db_index=True, max_length=24, unique=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('pad_width', models.PositiveSmallIntegerField(default=4)),
            ],
        ),
    ]
