# Generated by Django 5.2.7 on 2025-10-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('item_full_name', models.CharField(blank=True, max_length=512)),
                ('item_vasy_name', models.CharField(blank=True, max_length=512)),
                ('item_print_friendly_name', models.CharField(blank=True, max_length=512)),
                ('item_active', models.BooleanField(default=True)),
                ('hsn_code', models.CharField(blank=True, max_length=32)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('source_sheet', models.CharField(default='Item List', max_length=64)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['item_code'],
                'indexes': [models.Index(fields=['category'], name='taskmaster__categor_8492cf_idx'), models.Index(fields=['department'], name='taskmaster__departm_5027d6_idx')],
            },
        ),
    ]
