# Generated by Django 5.2.7 on 2025-11-04 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0002_employee_aadhaar_employee_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhaar',
            field=models.CharField(blank=True, default='', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be exactly 12 digits.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=18, validators=[django.core.validators.RegexValidator('^\\d{9,18}$', 'Account number must be 9–18 digits.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan',
            field=models.CharField(blank=True, default='', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10}$', 'PAN must be exactly 10 alphanumeric characters.')]),
        ),
    ]
