# Generated by Django 5.2.7 on 2025-11-19 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_loginlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WowBillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wow_min_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_per_wow', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wow_count', models.PositiveIntegerField(default=0)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exclude_returns', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wowbill_entries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wow_entries', to='outlets.employee')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wow_entries', to='outlets.outlet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
