# Generated by Django 5.2.7 on 2025-11-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_wowbillentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
