# Generated by Django 5.2.7 on 2025-12-02 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0006_employee_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhaar',
            field=models.CharField(blank=True, default='', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be exactly 12 digits.')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10}$', 'PAN must be exactly 10 alphanumeric characters.')]),
        ),
    ]
