# Generated by Django 5.2.7 on 2025-12-04 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0007_alter_employee_aadhaar_alter_employee_pan'),
        ('products', '0023_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wowbillentry',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wowbillentry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wow_entries', to='products.customer'),
        ),
        migrations.AddConstraint(
            model_name='wowbillentry',
            constraint=models.UniqueConstraint(fields=('employee', 'customer', 'bill_date'), name='uniq_wowbill_emp_customer_date'),
        ),
    ]
